# Generated by Django 6.0.6 on 2026-06-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groupes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupe',
            options={},
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='annee',
        ),
        migrations.RemoveField(
            model_name='groupe',
            name='description',
        ),
        migrations.AlterField(
            model_name='groupe',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
